name: Build Project (Windows Only)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - uses: ilammy/msvc-dev-cmd@v1

      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Configure & Build
        run: |
          cmake -S . -B build
          cmake --build build --config Release

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/
